// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List events (championships) visible to the signed-in user.",
  inputSchema: {
    only_active: z.boolean().optional().describe("Return only active events.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("events").select("id, name, description, edition, event_date, is_active, logo_url").order("event_date", { ascending: false });
    if (only_active) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-event-details.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_event_details_default = defineTool2({
  name: "get_event_details",
  title: "Get event details",
  description: "Get an event with its rules and prizes.",
  inputSchema: {
    event_id: z2.string().describe("Id of the event to fetch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: event, error } = await supabase.from("events").select("id, name, description, edition, event_date, is_active, logo_url, copa_year").eq("id", event_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!event) return { content: [{ type: "text", text: "Event not found or not visible to you." }], isError: true };
    const [{ data: rules }, { data: prizes }] = await Promise.all([
      supabase.from("event_rules").select("*").eq("event_id", event_id),
      supabase.from("event_prizes").select("*").eq("event_id", event_id)
    ]);
    const result = { event, rules: rules ?? [], prizes: prizes ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-teams.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_teams_default = defineTool3({
  name: "list_teams",
  title: "List teams",
  description: "List teams, optionally filtered by event id.",
  inputSchema: {
    event_id: z3.string().optional().describe("Event id to filter teams by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("teams").select("id, name, description, event_id, logo_url, primary_color, secondary_color, captain_id, created_at").order("created_at", { ascending: false });
    if (event_id) query = query.eq("event_id", event_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { teams: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-team.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_team_default = defineTool4({
  name: "get_team",
  title: "Get team details",
  description: "Get a single team with its members.",
  inputSchema: {
    team_id: z4.string().describe("Id of the team to fetch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ team_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: team, error } = await supabase.from("teams").select("id, name, description, event_id, logo_url, primary_color, secondary_color, captain_id, intro_video_url, created_at").eq("id", team_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!team) return { content: [{ type: "text", text: "Team not found or not visible to you." }], isError: true };
    const { data: members, error: membersError } = await supabase.from("team_members").select("id, user_id, classroom, classroom_group, joined_at").eq("team_id", team_id);
    if (membersError) {
      return { content: [{ type: "text", text: membersError.message }], isError: true };
    }
    const result = { team, members: members ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-my-teams.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
var list_my_teams_default = defineTool5({
  name: "list_my_teams",
  title: "List my teams",
  description: "List the teams the signed-in user belongs to.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("team_members").select("classroom, classroom_group, joined_at, teams(id, name, description, event_id, logo_url)").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { memberships: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-my-team.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z5 } from "npm:zod@^3.25.76";
var update_my_team_default = defineTool6({
  name: "update_my_team",
  title: "Update my team",
  description: "Update the name, description or colors of a team. Only allowed for teams the signed-in user is permitted to edit.",
  inputSchema: {
    team_id: z5.string().describe("Id of the team to update."),
    name: z5.string().optional().describe("New team name."),
    description: z5.string().optional().describe("New team description."),
    primary_color: z5.string().optional().describe("New primary color, e.g. #ff0000."),
    secondary_color: z5.string().optional().describe("New secondary color, e.g. #0000ff.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ team_id, name, description, primary_color, secondary_color }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const updates = {};
    if (name !== void 0) updates.name = name;
    if (description !== void 0) updates.description = description;
    if (primary_color !== void 0) updates.primary_color = primary_color;
    if (secondary_color !== void 0) updates.secondary_color = secondary_color;
    if (Object.keys(updates).length === 0) {
      return { content: [{ type: "text", text: "No fields to update." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("teams").update(updates).eq("id", team_id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "Team not updated \u2014 it does not exist or you do not have permission." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { team: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "twfbsgbydjuhqjjkhodv";
var mcp_default = defineMcp({
  name: "squad-event-maker",
  title: "squad-event-maker",
  version: "0.1.0",
  instructions: "Tools for squad-event-maker, an app for organizing team-based events (championships). Use list_events and get_event_details to explore events, list_teams/get_team to inspect teams, list_my_teams for the signed-in user's teams, and update_my_team to edit a team the user captains.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_events_default,
    get_event_details_default,
    list_teams_default,
    get_team_default,
    list_my_teams_default,
    update_my_team_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
